export enum ThemeType {
  LIGHT = "light",
  DARK = "dark",
  CUPCAKE = "cupcake",
  NIGHT = "night",
  DIM = "dim",
  LEMONADE = "lemonade",
  AUTUMN = "autumn",
  DRACULA = "dracula",
  VALENTINE = "valentine",
  RETRO = "retro",
  CYBERPUNK = "cyberpunk",
  FOREST = "forest",
  AQUA = "aqua",
  LOFI = "lofi",
}
